### ISSUE TITLE
todo from 9/20

### ISSUE THREAD

**Issue by dyurovsky** [meganwal/irregular-timing#1]
Corpus

- [ ] use current transcripts with media on/off tags to reproduce Emmi's analysis on more kids
- [ ] find out which other corpora have audio/video so we can manually code overregularization timing
- [ ] get a list of common overregularizations? Both past tense and plurals. Maybe try the Marcus monograph? https://www.jstor.org/stable/pdf/1166115.pdf?casa_token=-H_lA2jJn3cAAAAA:HdYoWLrMqPkPvuKIZEe5hnpcPZtU5WhhJHN8hvLnJALnlPvDteXqtAB6g2CJmW3d9_nHPmERGIoceQqhPrQ1gX2Mew4EJbxc6bGn56nvD_tVRO9XtyQ
- [ ] try using get_contexts to check for recasts like in Chouinard and Clark

Experiment

- [ ] brainstorm ideas where response could be a signal of inaccuracy. Trivia game? Escape room? Something like this would be a way of avoiding teaching people an artificial language
- [ ] we could try with stims that are novel but don't require learning a new language per se like tangrams. Here response time might be a signal of whether you gave a good explanation
- [ ] look for artificial grammar production studies to see if any are relatively quick. Might ask Bonnie?
